// chapters_1_4.js
// Out of Office: An Indian Professional's Misadventures Across India
// Chapters 1–4 — plain-object paragraph format

function chapter1() {
  return [
    { type: "heading", number: 1, title: "The Notification That Started It All" },

    { type: "first", text: "The fluorescent lights in our Koramangala office had a specific frequency of hum\u2014not quite a buzz, not quite a whine, but something in between that burrowed into the base of your skull and set up permanent residence. I\u2019d stopped noticing it months ago, the way you stop noticing the taste of the water in your city or the particular shade of grey that Bangalore\u2019s sky settles into during the week before monsoon. It was Monday morning, 9:47 AM, and I was staring at a Jira ticket titled \u201CQ3 Sprint Retrospective Action Items \u2014 URGENT\u201D with the kind of blank intensity that, from a distance, might have looked like deep concentration but was in fact the complete absence of thought." },

    { type: "body", text: "The ticket had been created by Vikram, my manager, at 11:43 PM on Sunday night, which told you everything you needed to know about Vikram and also about our company\u2019s relationship with the concept of weekends. It had seventeen sub-tasks, each one tagged with my name, each one highlighted in the red that Jira reserves for items that are both urgent and overdue. I scrolled through them with the enthusiasm of a man reading his own autopsy report." },

    { type: "body", text: "My coffee had gone cold forty minutes ago. Not the good kind of cold coffee\u2014the accidental kind, the kind that happens when you set a cup down to respond to a Slack message and then respond to fourteen more and then forget you were ever a person who had once been holding a warm beverage. The mug said \u201CKeep Calm and Deploy to Production\u201D in a font that was meant to be ironic. I\u2019d received it at the company offsite in Coorg two years ago, back when the company still had the budget for offsites and I still had the capacity to find deployment jokes amusing." },

    { type: "body", text: "From somewhere behind me\u2014the pantry, probably\u2014came the unmistakable smell of rajma chawal being reheated in the office microwave. It was Siddharth\u2019s. Siddharth always brought rajma chawal on Mondays, a fact I knew not because Siddharth and I were close but because the microwave was twelve feet from my desk and rajma has the kind of aroma that doesn\u2019t so much waft as *colonize*. The smell was warm and homey and deeply at odds with the spreadsheet in front of me, which contained action items that would require approximately three of me working in parallel to finish by Wednesday." },

    { type: "body", text: "My phone buzzed. Instagram. I should have ignored it. I had, in fact, made a solemn internal promise to myself at 9:15 AM that I would not check Instagram until lunch, a promise that had already been broken at 9:22, 9:31, and 9:38 AM. But this notification was different. It was from a travel page I\u2019d followed during a moment of aspirational weakness six months ago\u2014the kind of page that posts photos of places so beautiful they make your cubicle feel like a sensory deprivation chamber." },

    { type: "body", text: "The photo was of the living root bridges of Meghalaya: tangled, ancient, impossible structures grown by human hands over centuries, draped in mist and framed by jungle so green it looked like a color that hadn\u2019t been invented yet. The caption said something about \u201Cliving architecture\u201D and \u201Cpatience measured in decades.\u201D I double-tapped it before I could stop myself. My screen now showed a red heart floating over a bridge that had taken fifty years to grow, viewed by a man who couldn\u2019t wait fifty seconds for a build to compile." },

    { type: "body", text: "I stared at it. Then I looked at my Jira board. Then I looked at the photo again. The root bridges had been standing for five hundred years. My sprint retro action items were due by Wednesday. I opened a new browser tab\u2014my seventeenth\u2014and typed \u201CMakeMyTrip\u201D into the search bar. The tab now sat between \u201CJira \u2014 Q3 Sprint Board\u201D and \u201CStack Overflow \u2014 how to fix null pointer exception in Java\u201D, which felt like an accurate portrait of my inner life." },

    { type: "body", text: "Let me be clear about my travel credentials at this point. They were, to put it charitably, *thin*. There had been the family trip to Ooty when I was fourteen, during which my father had driven our Maruti 800 up forty-seven hairpin bends while my mother recited prayers and my sister threw up into a plastic bag from Nilgiris supermarket. I remember the hotel room smelled like mothballs and the \u201Crose garden\u201D was mostly thorns. We took one family photo in front of the lake and my father declared the trip a success." },

    { type: "body", text: "There had been the college trip to Goa, which was less a trip than a four-day argument about who owed whom money, punctuated by brief intervals of standing on a beach. Eight of us in one room. Somebody ate somebody else\u2019s Goan sausage. Alliances formed and dissolved. I came back with a sunburn and a conviction that group travel was a form of voluntary imprisonment." },

    { type: "body", text: "And there had been the company offsite to Coorg, which I\u2019d already mentioned and which had featured a \u201Cteam bonding\u201D rope course that gave me a friction burn on my left palm that took three weeks to heal. Our CTO had given a speech about \u201Cagility\u201D while we stood in a coffee plantation in business casuals, and I had written \u201Ckill me\u201D in my notes app and accidentally screen-shared it during the evening presentation." },

    { type: "body", text: "That was it. Twenty-six years old, and my entire travel history could fit on a Post-it note. I\u2019d never once planned a trip by myself, never booked a hotel room for one, never eaten a meal at a restaurant without at least one other person across the table. The idea of solo travel existed in my mind as something that other people did\u2014people in documentaries, people with trust funds, people who owned those expensive backpacks with the little water tube coming out the side." },

    { type: "body", text: "I had imagined it so clearly, too. Solo travel, in my head, looked like an Instagram carousel come to life. I would stand alone on a cliff at golden hour, arms slightly outstretched, face tilted toward the light in a way that suggested both spiritual depth and excellent cheekbones. There would be silence\u2014not the silence of my PG accommodation when the WiFi router died, but the *meaningful* kind, the kind that fills you with cosmic understanding. I would journal in a leather-bound notebook. I would have profound conversations with weathered old men who spoke in aphorisms. I would return to Bangalore radiating an aura of inner peace that my colleagues would notice and envy. \u201CYou seem different,\u201D they\u2019d say. \u201CI am,\u201D I\u2019d reply, cryptically, and walk away trailing the faint scent of mountain air." },

    { type: "body", text: "This is the version of solo travel that exists before you\u2019ve actually done it. It is a fantasy as detailed and as wrong as any fantasy has ever been. But I didn\u2019t know that yet. All I knew was that I was staring at a photo of root bridges on a Monday morning, and something inside me\u2014some small, neglected organ whose only function was to want things\u2014was making a sound I hadn\u2019t heard in a long time." },

    { type: "break" },

    { type: "first", text: "I don\u2019t know what made me do it. Maybe it was the root bridges. Maybe it was the rajma chawal reminding me that Mondays were always going to smell exactly the same. Maybe it was the seventeenth red-highlighted action item. But at 10:14 AM on a Monday in October, I searched for \u201Cweekend trips from Bangalore\u201D and started scrolling." },

    { type: "body", text: "Hampi came up on every list. I\u2019d heard of it vaguely\u2014something about ruins, something about boulders, something about a place where hippies went to find themselves. The photos showed landscapes that looked photoshopped: massive rust-colored boulders balanced on top of each other like a giant\u2019s abandoned game of marbles, ancient temples rising out of banana plantations, a river that wound through it all like a green ribbon somebody had dropped from a helicopter." },

    { type: "body", text: "The bus from Bangalore was seven hours. The cheapest ticket was Rs. 4,200 for a Friday night departure with return on Sunday night. I could take no leave at all\u2014just a weekend. A weekend. The same amount of time I usually spent watching Netflix and feeling vaguely guilty about not exercising." },

    { type: "body", text: "My finger hovered over the \u201CBook Now\u201D button for eleven seconds. I know this because I counted. In those eleven seconds, a miniature parliament convened inside my head. The Minister of Responsibility pointed out the sprint retro. The Minister of Finance noted that Rs. 4,200 was not nothing. The Minister of Social Anxiety asked who would I even talk to for two days. The Minister of Whatever-This-Feeling-Is\u2014the one who\u2019d been staring at root bridges instead of Jira tickets\u2014said, simply, *just book it*." },

    { type: "body", text: "I booked it. The confirmation email arrived with a cheerful \u201CYour Adventure Awaits!\u201D subject line that made me feel like I\u2019d done something either very brave or very stupid. I submitted a leave request for the Friday: \u201CPersonal day \u2014 prior commitment.\u201D Vikram approved it within three minutes with a response that said \u201CSure\u201D followed by a period. Not an exclamation mark. Not a \u201Chave fun.\u201D A period. The kind of period that says *I\u2019m noting this*." },

    { type: "body", text: "I told no one. Not Siddharth, not my PG roommate, not my parents. The trip existed in a sealed chamber of my brain, protected from external opinions. I knew\u2014with the intuition of a man who has been talked out of things his entire life\u2014that if I told anyone, the trip would dissolve. Someone would ask a practical question. Someone would raise a concern. Someone would say \u201Calone?\u201D in that particular tone that makes \u201Calone\u201D sound like a medical diagnosis. So I kept it to myself, a small, glowing secret sitting next to my seventeenth Jira ticket." },

    { type: "body", text: "The rest of the week was a blur of packing anxiety. I made a list, crossed it out, made another list, googled \u201Cwhat to pack for Hampi,\u201D found seventeen contradictory blog posts, and ended up packing for what appeared to be three separate trips: a beach vacation, a mountain expedition, and a business meeting. My backpack weighed nine kilograms, which I would later learn was approximately seven kilograms too many for a weekend in a place where the average temperature was thirty-four degrees." },

    { type: "body", text: "Thursday night, I almost cancelled. I was lying in bed in my PG accommodation in HSR Layout, staring at the ceiling fan making its arthritic rotations, and the whole idea suddenly seemed absurd. Who goes to Hampi alone? What was I going to *do* there? Take selfies in front of ruins? Eat meals by myself while couples at adjacent tables had conversations? My phone lit up with an email notification. Subject line: \u201CURGENT: Q3 Sprint Retro Follow-Up \u2014 Action Required Before Monday.\u201D I read it twice. Then I set my alarm for 4:30 AM and turned off the light." },

    { type: "break" },

    { type: "first", text: "The KSRTC bus departed from Majestic Bus Station at 11 PM on Friday, and Majestic at 11 PM is a place that could charitably be described as *organized chaos* and more accurately described as a dimension where the normal rules of physics and queuing do not apply. Buses idled in clouds of diesel smoke. Conductors shouted destinations into the crowd like auctioneers. A man was asleep on a concrete bench with a newspaper over his face, apparently unbothered by the fact that three hundred people were milling around him at full volume." },

    { type: "body", text: "I found my bus\u2014a semi-sleeper with curtains that had once been purple and were now the color of regret\u2014and climbed into my berth. The seat reclined to an angle that was exactly wrong: too upright to sleep, too reclined to sit. The man in the berth next to mine was already snoring with a commitment that suggested he\u2019d been training for this his entire life. His snores had range\u2014low rumbles that built to a crescendo, paused dramatically, and then resumed with renewed vigor, like a symphony conducted by a sleeping walrus." },

    { type: "body", text: "I put in my earphones, pressed play on a Spotify playlist called \u201CCalm Vibes,\u201D and watched Bangalore slide past the window. The city thinned out in stages. First the malls disappeared, then the apartment complexes, then the construction sites, until there was nothing but highway and darkness and the occasional flash of a truck going the other direction. The air changed\u2014the diesel and dust of the city giving way to something cleaner, something that smelled like night and open land and the faintest hint of burning paddy fields." },

    { type: "body", text: "I checked Google Maps obsessively, convinced I would miss my stop, which was irrational because the bus was going to Hospet and Hospet was the last stop, but first-timer paranoia doesn\u2019t answer to logic. Every time the bus slowed down\u2014for a toll booth, for a speed breaker, for a cow standing in the road with the patient entitlement of a creature that knows it has right of way\u2014my heart rate spiked." },

    { type: "body", text: "I must have slept, because when I next opened my eyes, the landscape had changed completely. The highway was gone. Banana plantations lined the road in neat rows, their broad leaves catching the first grey light of pre-dawn. Then the plantations gave way to open scrubland, dry and flat and dotted with termite mounds that rose from the earth like small red castles." },

    { type: "body", text: "And then\u2014suddenly, as if the earth had decided to show off\u2014the boulders appeared. They were enormous. Not large-rock enormous but *impossible* enormous, balanced on top of each other in configurations that defied gravity and common sense. Rust-colored, smooth, stacked like a child\u2019s building blocks left behind by a child the size of a mountain. The bus was pulling into Hospet at 6 AM, and through the smudged window I could see these ancient granite formations catching the first orange light of sunrise." },

    { type: "body", text: "Hospet at 6 AM was a town still waking up. Three chai stalls were open at the bus stand, their kerosene stoves hissing blue flames under steel kettles, steam rising into the cool morning air. Stray dogs moved between the stalls with the practiced efficiency of animals who knew exactly which vendor dropped the most biscuit crumbs. The air smelled like diesel and chai and the fine red dust that would coat everything I owned for the next two days. I stood on the platform with my nine-kilogram backpack and my phone showing the GPS dot that confirmed I was, in fact, 350 kilometres from my cubicle, and I felt\u2014for the first time since I\u2019d hit that \u201CBook Now\u201D button\u2014a rush of something that I can only describe as *aliveness*." },

    { type: "break" },

    { type: "first", text: "The auto driver at Hospet bus stand took one look at my overstuffed backpack, my confused expression, and my phone open to Google Maps, and quoted me Rs. 400 for a ride that, I would later learn, should have cost Rs. 150. This is a travel tax that every first-timer pays, and I paid it with the cheerful ignorance of a man who didn\u2019t know any better. The auto rattled down a road that wound between boulders and banana groves, and twelve minutes later, deposited me at the entrance to Hampi." },

    { type: "body", text: "Virupaksha Temple at 7 AM is a different creature than Virupaksha Temple at noon. At noon, it\u2019s a tourist site\u2014guides hawking their services, vendors selling coconuts and postcards, crowds jostling for selfie angles in front of the gopuram. At 7 AM, it\u2019s what it\u2019s been for thirteen hundred years: a place of worship. The eastern gopuram\u2014fifty metres tall, covered in carved figures so intricate they seemed to move in the shifting light\u2014glowed the color of turmeric in the morning sun." },

    { type: "body", text: "A priest was performing the opening puja inside the main sanctum, his chanting echoing off stone walls that had absorbed thirteen centuries of prayer. The sound was not melodic, exactly, but it had a rhythm that felt older than music\u2014a vibration that you felt in your sternum before you heard it in your ears. I took off my shoes and walked through the outer courtyard barefoot. The stone was cool under my feet, not yet baked by the day\u2019s heat." },

    { type: "body", text: "A temple elephant named Lakshmi was being led to her bath by her handler, her massive feet surprisingly delicate on the ancient paving stones. She paused as she passed me, and her handler said something in Kannada that I didn\u2019t understand, but Lakshmi apparently did, because she lifted her trunk and gently touched the top of my head. The handler laughed. \u201CBlessings,\u201D he said in English. \u201CFree today.\u201D" },

    { type: "body", text: "I want to say I felt something spiritual. I want to say that standing inside a temple that has been in continuous operation since the seventh century\u2014longer than most countries have existed\u2014produced some kind of transcendental awakening. It didn\u2019t. What I felt was simpler and, I think, more honest: I felt *present*. For the first time in months, possibly years, I was not thinking about a Jira ticket or a Slack message or a sprint deadline. I was standing barefoot on cool stone, listening to chanting that had been going on for over a thousand years, and I was *here*. That was enough." },

    { type: "body", text: "The rest of the morning was a self-guided tour of ruins so vast they made my head spin. The stone chariot at Vittala Temple, carved from a single piece of granite, every wheel functional, the entire structure so detailed that I spent twenty minutes just looking at one corner of it. The elephant stables\u2014eleven domed chambers in a row, each one large enough to house a war elephant, their arched doorways framing the boulder-strewn landscape beyond like enormous picture frames." },

    { type: "body", text: "And then the underground Shiva temple, which nobody at the hostel had mentioned and which I found only because I got lost. The entrance was a narrow staircase leading down into darkness. I turned on my phone flashlight and descended. At the bottom, knee-deep in cool water that had seeped in from the Tungabhadra River, stood a Shiva lingam draped in wet marigolds. The ceiling was low. The air was damp and still and smelled of stone and river water. I was alone. The only sound was the gentle lapping of water against the lingam\u2019s base." },

    { type: "body", text: "I stood there for five minutes, maybe ten, in the silence of a temple that had been underwater and forgotten and rediscovered, and I felt something rearrange itself inside my chest\u2014some tightly wound spring that I hadn\u2019t known was there beginning to loosen." },

    { type: "body", text: "Lunch was a Rs. 120 thali at a rooftop restaurant overlooking the river. Rice, sambar, rasam, two vegetable curries, pickle, papad, and a sweet that I couldn\u2019t identify but that tasted like cardamom and joy. The restaurant owner, a cheerful man with a thick mustache and a lungi rolled up to his knees, asked where I was from. \u201CBangalore,\u201D I said. He nodded knowingly. \u201CIT, boss?\u201D I nodded. He laughed, the kind of laugh that comes from having watched this exact scene play out a thousand times. \u201CYou all come here looking the same,\u201D he said, pouring me a glass of buttermilk I hadn\u2019t asked for. \u201CTired. Something in the eyes. In two days you look different. The boulders fix it. I don\u2019t know how, boss, but they fix it.\u201D" },

    { type: "body", text: "I ate slowly, which was unusual for me\u2014in Bangalore, meals were things I did between meetings, inhaled at my desk or shoveled down during the twenty-minute lunch break. Here, there was nobody waiting for me. No 1:30 PM standup. No \u201Cquick sync\u201D that would inevitably last forty-five minutes. Just rice, sambar, and a view of boulders that had been sitting in the same spot since the Mesozoic era." },

    { type: "body", text: "I spent six hours that day talking to no one. This was, I realized, the longest I\u2019d gone without speaking to another human being since\u2026 I genuinely couldn\u2019t remember. In Bangalore, there was always someone: the auto driver, the chai wallah, the colleague who stopped by your desk, the roommate who wanted to discuss whether the WiFi was slower than usual (it was always slower than usual). Here, the silence wasn\u2019t lonely. It was spacious. It had room in it. Room for thoughts that weren\u2019t about deadlines, room for noticing things\u2014the way the light changed on the stone throughout the day, the way lizards basked motionless on the boulders, the way the river sounded different depending on where you stood." },

    { type: "break" },

    { type: "first", text: "I climbed Hemakuta Hill at 5:30 PM, following a path that wound between boulders and small ruined temples. Other travelers were already there\u2014a couple sharing a shawl on a flat rock, a group of backpackers passing around a bag of chips, a man in saffron robes sitting cross-legged with his eyes closed, perfectly still. I found my own boulder\u2014warm from the day\u2019s sun, angled like a recliner\u2014and sat down." },

    { type: "body", text: "What happened next was not dramatic. There was no epiphany, no shaft of light, no background music swelling to a crescendo. The sun went down over Hampi, and it was\u2014I\u2019m going to use this word deliberately\u2014*beautiful*. Not Instagram-beautiful, not filtered-and-hashtagged beautiful, but beautiful in the way that makes the word feel insufficient. The sky went through every shade of orange and purple and pink that exists, and a few that I\u2019m fairly certain don\u2019t, and the light bounced off the boulders and the gopurams and the river below until the whole landscape looked like it was on fire." },

    { type: "body", text: "The Tungabhadra River caught the colors and held them, its surface turning from green to gold to deep violet as the sun dropped lower. Coracles\u2014round, bowl-shaped boats that looked like they had no business floating\u2014dotted the river, their oarsmen silhouetted against the water. On the far bank, the palm trees of Hippie Island swayed in a breeze I couldn\u2019t feel. Somewhere below, a temple bell rang, its sound carrying up the hill clear and clean in the cooling air." },

    { type: "body", text: "My phone buzzed. I looked at it out of reflex\u2014the Pavlovian response of a generation raised on notifications. It was a Slack message from Priya, a colleague: \u201CHey, can you review this PR when you get a chance? No rush but Vikram wants it merged by Monday.\u201D No rush, but Monday. The eternal paradox of corporate communication." },

    { type: "body", text: "I looked at the message. I looked at the sunset. The boulders were turning from orange to deep red, and two kids were running between them, their laughter carrying up the hill in bright, clean bursts. An old woman was lighting a lamp in one of the small hilltop temples, the flame catching and holding, adding its tiny warmth to the larger warmth of the sky." },

    { type: "body", text: "I put my phone on Do Not Disturb. Then I opened Slack and changed my status. I deleted the default \u201CIn a meeting\u201D and the passive-aggressive \u201CFocusing\u201D and typed two words: **Out of Office**. I added the little palm tree emoji because it was there. Then I put the phone face-down on the warm granite and watched the last sliver of sun disappear behind the horizon." },

    { type: "body", text: "It was the first honest status I\u2019d ever set. Every other status had been a performance\u2014\u201CAvailable\u201D when I wasn\u2019t, \u201CBusy\u201D when I was just avoiding people, \u201CLunch\u201D when I was eating at my desk. But this one was true. I was out of the office. I was out of Koramangala, out of the sprint board, out of the fluorescent hum. I was sitting on a warm boulder on a hill in Hampi, watching the sky do things that no Jira ticket would ever require me to document, and I was\u2014for the first time in a long time\u2014exactly where I wanted to be." },

    { type: "body", text: "I didn\u2019t know it yet, but that status would become my identity. And my next trip\u2014a disaster I\u2019m still embarrassed about\u2014was only three weeks away." },

    { type: "trip", destination: "Hampi", items: [
      ["Duration", "2\u20133 days (Friday\u2013Sunday from Bangalore)"],
      ["Budget", "Rs. 5,000\u20137,000 (including transport, stay, food, and autos that overcharge you)"],
      ["Best Season", "October\u2013February (avoid summer unless you enjoy sweating through your clothes by 9 AM)"],
      ["Getting There", "Overnight KSRTC bus from Bangalore Majestic to Hospet (Rs. 800\u20131,200, 7 hours). Auto from Hospet to Hampi (Rs. 150\u2014negotiate hard)."],
      ["Where to Stay", "Hippie Island (Virupapur Gaddi) for hostels and guesthouses, Rs. 400\u2013800/night. Cross the river by coracle (Rs. 50). Hampi Bazaar side for temple proximity."],
      ["Must-Try Food", "Rooftop thali at Mango Tree or Laughing Buddha (Rs. 100\u2013150). Fresh sugarcane juice from the stalls near Virupaksha. Banana chips everywhere."],
      ["One Tip", "Rent a bicycle (Rs. 150/day) and explore the ruins at your own pace. The sites are spread across 26 sq km\u2014autos add up fast. A bicycle gives you the freedom to get lost, which is the whole point."],
    ]},
  ];
}

function chapter2() {
  return [
    { type: "heading", number: 2, title: "My First Solo Trip Was a Beautiful Disaster" },

    { type: "first", text: "I was standing in the rain in a town whose name I couldn\u2019t pronounce, with a dead phone, no hotel booking, and exactly forty-seven rupees in my pocket. Let me say that again, because the specificity matters: *forty-seven rupees*. Not fifty, which would at least be a round number with a shred of dignity. Forty-seven. A twenty, a ten, two fives, a two-rupee coin, and five one-rupee coins that I had counted twice in the desperate hope that counting them again would produce a different total." },

    { type: "body", text: "The rain was not the romantic, cinematic kind that falls gently on the protagonist while a piano plays in the background. This was Coorg rain\u2014thick, vertical, personal, the kind that doesn\u2019t fall so much as *arrive*, all at once, like someone upended a lake directly above your head. My shoes had surrendered their waterproof pretensions about two hours ago. My backpack\u2019s rain cover, which I\u2019d bought specifically for this trip and tested in my bathroom using the shower head, had developed a leak in the one spot directly above my change of clothes. And this\u2014this wet, miserable, forty-seven-rupee version of me\u2014was not in Madikeri, the town I had planned and paid and spreadsheet-optimized my way to. I was in Makkandur. Makkandur! A town that didn\u2019t even appear on Google Maps unless you zoomed in so far you could practically count the roof tiles." },

    { type: "body", text: "The bus driver had dropped me here. Not maliciously\u2014I want to be fair to the man. He had shouted something from the front of the bus, something that sounded approximately like \u201CMadikeri\u201D if you were sleep-deprived and hadn\u2019t accounted for the fact that the Karnataka State Road Transport Corporation does not provide stop announcements in English, or in any language that my north-Indian ears could parse through the combined noise of an aging diesel engine, Kannada film songs at full volume, and a rooster that someone had brought aboard in a cardboard box at the previous stop." },

    { type: "body", text: "I had grabbed my backpack and jumped off the bus with the confidence of a man who was wrong. The bus had pulled away. The road was empty. The rain had started. And I was standing in Makkandur, which was not Madikeri, with a phone at three percent battery and the slowly crystallizing realization that my spreadsheet\u2014my beautiful, color-coded, pivot-tabled Google Sheet\u2014was completely, catastrophically useless." },

    { type: "body", text: "The panic was not the cute, anecdotal kind that looks good in a travel essay. It was genuine, stomach-tightening panic\u2014the kind where your body decides that the appropriate response to an uncertain situation is to make your hands shake and your throat close up. I was alone. No one knew where I was. The nearest familiar face was in Bangalore, seven hours away. The nearest ATM was\u2014I had no idea where the nearest ATM was, because I was in a town I hadn\u2019t known existed until three minutes ago." },

    { type: "body", text: "I stood under the tin awning of a closed shop and tried to think clearly, which is difficult when you\u2019re wet and scared and the inside of your shoes has achieved a consistency best described as *swamp*. My phone screen was dimming, the battery icon red and accusatory. I could make one call, maybe two, before it died." },

    { type: "body", text: "And then, because this is India and India has a way of intervening precisely when you need it to, a man appeared. He came walking up the road in the rain, holding a black umbrella in one hand and a bunch of bananas in the other, wearing a white shirt that had no business being that clean in this weather. He was perhaps sixty, short, sturdy, with the kind of face that looked like it had been weathered by a lifetime of monsoons and had decided to be cheerful about it." },

    { type: "body", text: "He stopped when he saw me. He took in the backpack, the soaked clothes, the expression of a man whose dignity had been dissolved by rain. He said something in Kodava. I shook my head. He tried Kannada. I shook my head again. He tilted his head, assessed me with the efficiency of a man who had seen lost people before, and said, in English that was slow and careful and perfectly clear: \u201CWhere you going?\u201D" },

    { type: "body", text: "\u201CMadikeri,\u201D I said. My voice came out smaller than I\u2019d intended. He nodded, unsurprised. \u201CWrong place,\u201D he said. \u201CMadikeri is there.\u201D He pointed into the rain, in a direction that contained no visible road, no visible town, and no visible reason for optimism. \u201CFifteen kilometres.\u201D" },

    { type: "body", text: "Fifteen kilometres. In this rain. With forty-seven rupees. He must have seen something in my face\u2014desperation, probably, or maybe just the universal expression of a young person who has gotten themselves into a situation they cannot get themselves out of\u2014because he held the bananas toward me and said, \u201CEat. Then we go.\u201D" },

    { type: "body", text: "I took a banana. I peeled it and ate it standing there in the rain under a tin awning in a town called Makkandur, and it was, without exaggeration, the best banana I have ever eaten. Not because there was anything special about the banana itself, but because I was being fed by a stranger who had decided that my problem was his problem, and that combination\u2014hunger, fear, relief, and an unexpected act of kindness\u2014has a flavor that no fruit can replicate on its own." },

    { type: "break" },

    { type: "first", text: "Let me go back. Let me go back to the version of me who thought this trip would be easy\u2014who had, in the ten days since returning from Hampi, inflated that modest weekend success into a conviction that he was now, essentially, Bear Grylls with a laptop." },

    { type: "body", text: "The plan had been exquisite. I know this because I had built it in Google Sheets\u2014color-coded, time-stamped, with conditional formatting that turned cells green when an activity was confirmed and red when it was still tentative. Column A was the time slot. Column B was the activity. Column C was the estimated cost. Column D was the \u201CNotes\u201D column, which contained helpful reminders like \u201CBring mosquito repellent\u201D and \u201CDon\u2019t forget to actually enjoy yourself.\u201D" },

    { type: "body", text: "I had even created a pivot table. For a vacation. I am not proud of this, but I am honest about it." },

    { type: "body", text: "The itinerary covered three days in Coorg and was, in retrospect, the work of a man who had confused a holiday with a military operation. Day 1: Arrive Madikeri by noon, check into the homestay, visit Abbey Falls (2 PM\u20133:30 PM), sunset at Raja\u2019s Seat (5 PM\u20136:30 PM), dinner at a \u201Chighly rated\u201D restaurant I\u2019d found on Zomato. Day 2: Dubare Elephant Camp at dawn, coffee plantation tour at 2 PM, Namdroling Monastery at 4 PM. Day 3: Leisure morning\u2014my spreadsheet\u2019s way of acknowledging that human beings occasionally need rest\u2014followed by departure at 2 PM." },

    { type: "body", text: "I\u2019d imagined the whole thing so clearly. I would arrive at a charming homestay surrounded by coffee plants, drink filter coffee on the veranda while mist rolled through the valley below, and spend three days in a state of photogenic tranquility. I would post tasteful photos on Instagram\u2014nothing flashy, just a coffee cup in the foreground and green hills in the background, the visual equivalent of saying \u201CI\u2019m cultured and relaxed and you should be jealous.\u201D I would return to Bangalore renewed, my spreadsheet complete, every cell turned green." },

    { type: "body", text: "That is not what happened." },

    { type: "break" },

    { type: "first", text: "The man with the bananas and the umbrella walked me to a house about ten minutes down a side road. The house belonged to his cousin, a woman named Asha who operated an informal homestay\u2014the kind that doesn\u2019t appear on any booking website, doesn\u2019t have a Zomato rating, and whose existence is communicated entirely through the network of people who know people who know Asha." },

    { type: "body", text: "Asha\u2019s cousin deposited me at the front door, spoke rapidly to Asha in Kodava, patted me once on the shoulder\u2014firmly, the way you\u2019d reassure a large, confused animal\u2014and disappeared back into the rain. I never saw him again. I never learned his name. He had materialized out of the monsoon with a banana and an umbrella, solved my problem, and vanished, and I was left standing in Asha\u2019s doorway, dripping water onto her stone floor, wondering if the universe had a customer service department that I should be writing a thank-you note to." },

    { type: "body", text: "Asha was a compact woman in her fifties with reading glasses pushed up into her hair and the brisk, efficient manner of someone who has fed many unexpected people at short notice and considers it routine. She looked at me. She looked at the puddle forming around my feet. She said, \u201CRice and sambar, ten minutes,\u201D and walked into the kitchen." },

    { type: "body", text: "The rice and sambar arrived on a steel plate at 10 PM. It was not a remarkable meal by any objective standard\u2014plain white rice, sambar with drumstick and brinjal, a lime pickle on the side, a glass of water. But I was soaking wet and starving and alone in a stranger\u2019s house in a town I\u2019d never heard of, and the warmth of that plate\u2014the literal, physical warmth of it in my cold hands, and the other kind of warmth, the kind that comes from being fed when you need feeding\u2014was overwhelming." },

    { type: "body", text: "I ate everything. Asha watched from the kitchen doorway with her arms crossed, performing the ancient Indian evaluation of whether a guest has eaten enough, and apparently concluded that I had not, because she returned with a second helping of rice and a small bowl of payasam that she set down without comment." },

    { type: "body", text: "Lying in bed that night\u2014a narrow cot with a thin mattress and a surprisingly warm blanket\u2014I stared at the ceiling and listened to the rain hammering on the Mangalore tiles above me. My phone was charging in the corner, slowly resurrecting. My spreadsheet was a graveyard of red cells. I had not visited Abbey Falls. I had not seen the sunset at Raja\u2019s Seat. I had not checked into any homestay that appeared on any website. I was in Makkandur, and Makkandur was not on the itinerary." },

    { type: "body", text: "And then I laughed. Not a polite, social laugh\u2014a real one, the kind that starts in your stomach and works its way up and surprises you because you didn\u2019t know it was coming. I laughed because I was alive and dry and fed, and the gap between what I had planned and what had actually happened was so vast it was funny. The Instagram version of solo travel\u2014peaceful solitude, golden light, the contemplative coffee on the misty veranda\u2014was a fantasy. The reality was standing in the rain, needing a stranger\u2019s help, and feeling like an idiot. And the reality was, somehow, *better*." },

    { type: "break" },

    { type: "first", text: "The next two days were improvised from scratch. Asha\u2019s cousin returned the next morning on a scooter and offered to show me around\u2014not the tourist attractions, not the Abbey Falls and Raja\u2019s Seat of my spreadsheet, but the Coorg he knew. This was how I found myself walking through a coffee plantation at 7 AM, mist hanging in the canopy like gauze, the air so thick with the smell of coffee flowers that I felt mildly intoxicated." },

    { type: "body", text: "A dog appeared from nowhere and fell into step beside me. He was brown, medium-sized, with one ear that stood up and one that flopped down, giving him a permanent expression of lopsided curiosity. Asha\u2019s cousin called him Buddy, though it was unclear whether this was the dog\u2019s name or a general term of address. Buddy walked with me for two hours through the plantation, trotting ahead on the trail, pausing to wait when I fell behind, occasionally looking back over his shoulder with an expression that said, very clearly, *keep up*." },

    { type: "body", text: "We found a waterfall. Not a tourist waterfall\u2014not a waterfall with a parking lot and a ticket counter and a sign saying \u201CDangerous: Do Not Swim.\u201D A waterfall that existed at the end of a trail that existed because people and animals had walked it enough times to wear the vegetation down. It was maybe fifteen feet tall, pouring over a mossy ledge into a pool that was brown with tannins and cold enough to make me gasp when I waded in up to my knees." },

    { type: "body", text: "A kid appeared on the trail above us\u2014couldn\u2019t have been more than ten, barefoot, carrying a stick that was taller than he was. He looked at me standing knee-deep in the pool and grinned the grin of a child who has watched many adults discover this place and found each one entertaining. He pointed down the trail and said something that Asha\u2019s cousin translated as: \u201CThere\u2019s a better one further down.\u201D There was. A cascade of three smaller falls, each emptying into the next, hidden behind a screen of ferns so dense you couldn\u2019t see them from the main trail." },

    { type: "body", text: "Lunch was at a place that didn\u2019t have a menu. It was a concrete building with four plastic tables and a kitchen that produced food based on what was available that day, which turned out to be ragi mudde and akki roti with a pork curry that bore a family resemblance to the pandi curry I\u2019d read about but was wilder, fiercer, made with spices that I suspected came from the garden out back." },

    { type: "body", text: "The ragi mudde was a revelation. A dense ball of finger millet, dark as chocolate, with a texture that was simultaneously smooth and substantial\u2014like bread crossed with a dumpling. You tore off pieces and dipped them in the curry, and the combination\u2014the earthy, nutty millet and the spicy, tangy pork\u2014was so right that it felt less like eating and more like discovering something that had been waiting for you." },

    { type: "body", text: "The akki roti was thin and crispy, made from rice flour and flecked with carrot and cumin, cooked on a flat griddle until the edges were brown and lacy. I ate three of them. The woman running the kitchen watched me eat the third one with the quiet satisfaction of a person who has made ten thousand akki rotis and knows, without needing to be told, when one has been appreciated." },

    { type: "body", text: "That afternoon, Asha\u2019s cousin took me to his family\u2019s coffee estate. Not a tourist plantation visit with a guide and a gift shop\u2014the actual working estate where his family grew and processed coffee. He showed me the plants, explained the difference between arabica and robusta, let me taste a coffee cherry straight from the branch (it was sweet, nothing like coffee, which surprised me the way it surprises everyone). He showed me the drying beds where the beans lay spread in the sun, and the room where they were roasted, and the ancient hand grinder his grandmother still used." },

    { type: "body", text: "He brewed me a cup. It was, inevitably, the best coffee I\u2019d ever had, because it had been grown and roasted and ground and brewed within a radius of fifty feet, and because the man who brewed it had done so with the care of someone sharing something personal." },

    { type: "break" },

    { type: "first", text: "The departure was the hardest part. On Sunday morning, Asha packed me a lunch for the bus: rice, pickle, and a Kodava pork fry wrapped in banana leaf. Her cousin walked me to the main road where the bus to Bangalore would stop. I tried to pay for the room, the food, the two days of hospitality that had materialized out of a disaster." },

    { type: "body", text: "He refused. Not with the polite, performative refusal that precedes eventually accepting\u2014the kind where you push the money back and forth three times before it\u2019s taken. He refused with the finality of a man stating a fact. \u201CGuests don\u2019t pay,\u201D he said. \u201CYou came to our home. You are a guest. This is how it works.\u201D" },

    { type: "body", text: "I got on the bus with my still-damp backpack, my banana-leaf lunch, a bag of estate coffee that Asha had pressed into my hands at the door, and zero\u2014precisely zero\u2014of the planned attractions visited. I had not seen Abbey Falls. I had not visited Dubare Elephant Camp. I had not watched the sunset at Raja\u2019s Seat. I had not taken a single Instagram-worthy photo. My spreadsheet was a ruin." },

    { type: "body", text: "And it was the best trip I had ever taken. Not despite the disasters, but because of them. Because the disasters had stripped away the plan, and underneath the plan was something I hadn\u2019t expected: kindness. Strangers who gave bananas and umbrellas and scooter rides and rice and sambar and coffee and two days of their lives to someone they\u2019d never met and would probably never see again. This was not the travel I\u2019d imagined. It was better." },

    { type: "body", text: "The worst trips make the best stories. This is a clich\u00e9, and I used to roll my eyes at it, the way you roll your eyes at anything that shows up on a motivational poster. But sitting on that bus, watching the coffee plantations give way to highway, eating Asha\u2019s pork fry out of a banana leaf, I understood it for the first time. The trips that go according to plan disappear from memory. They become \u201Cnice.\u201D Nice hotel, nice view, nice time. The trips that go wrong become *stories*. They become the thing you tell at dinner parties, the thing you laugh about with strangers, the thing that teaches you what you\u2019re actually made of." },

    { type: "body", text: "I got home on Sunday night, sunburned and slightly feverish, and did something I\u2019d never done before: I opened my calendar and started counting holidays." },

    { type: "trip", destination: "Coorg (Madikeri)", items: [
      ["Duration", "3 days (long weekend from Bangalore)"],
      ["Budget", "Rs. 6,000\u20139,000 (less if a kind Kodava family takes you in, which you cannot plan for and should not expect)"],
      ["Best Season", "October\u2013March for clear skies; monsoon (June\u2013September) for drama, waterfalls, and the risk of becoming a cautionary tale"],
      ["Getting There", "KSRTC bus from Bangalore to Madikeri (5\u20136 hours, Rs. 600\u2013900). Or drive if you have a car AND enjoy hairpin bends."],
      ["Where to Stay", "Book VERIFIED homestays only\u2014check Google Maps street view, read recent reviews, call ahead. If the photos look too good, they probably are."],
      ["Must-Try Food", "Pandi curry (Coorgi pork curry with kachampuli vinegar), ragi mudde, akki roti, and filter coffee from a local estate"],
      ["One Tip", "Get off the tourist trail. The best Coorg experiences\u2014the hidden waterfalls, the family estates, the meals with no menu\u2014are found through people, not Google. Talk to your homestay host. Ask where *they* would eat. Follow the dog named Buddy."],
    ]},
  ];
}

function chapter3() {
  return [
    { type: "heading", number: 3, title: "The Art of the Long Weekend" },

    { type: "first", text: "January 2nd. The office was half-empty, still hungover from New Year\u2019s, running on the skeletal crew of people who either didn\u2019t celebrate or celebrated so efficiently that they were functional by 9 AM. I was at my desk with a cup of filter coffee from the new machine that HR had installed as a morale initiative, staring at something that would change my life more profoundly than any mountain or temple or midnight bus: the company holiday calendar." },

    { type: "body", text: "It was a PDF. A single-page PDF, formatted in the company\u2019s brand colors\u2014teal and white, the colors of corporate optimism\u2014listing every public holiday, restricted holiday, and optional holiday for the calendar year. Most people glanced at it, noted Diwali and Christmas, and filed it away. I was not most people. Not anymore. Because sitting there, coffee in hand, still carrying the sunburn from Hampi and the faint smell of Coorg coffee on a jacket I hadn\u2019t washed yet, I saw the calendar not as a list of days off but as a *map*." },

    { type: "body", text: "The revelation hit me the way all good revelations do: suddenly and obviously, as if it had been sitting in plain sight the whole time and I\u2019d been too busy filling out sprint retrospective forms to notice. The magic was in the *gaps*. Not the holidays themselves\u2014everyone gets excited about Diwali week or Christmas\u2014but the lonely Thursdays and Mondays, the public holidays that fell one day away from a weekend, separated by a single working day that stood between you and freedom like a bureaucratic toll booth." },

    { type: "body", text: "I opened Google Sheets. Of course I opened Google Sheets. I am a man who responds to inspiration the way other people respond to fire alarms: with a spreadsheet. Column A: Holiday Name. Column B: Day of the Week. Column C: Adjacent Weekend Days. Column D: Leave Days Needed. Column E: Total Trip Days. Column F\u2014and this was the column that made me feel like a criminal mastermind\u2014was labeled **ROI**, because I had calculated the ratio of trip days to leave days used and discovered that the numbers were, frankly, *obscene*." },

    { type: "body", text: "Republic Day fell on a Thursday. Take Friday off: four-day trip, one leave day used. ROI: 4.0. Independence Day fell on a Wednesday. Take Thursday and Friday off: five-day trip, two leave days. ROI: 2.5. Holi fell on a Monday. No leave needed: three-day trip, zero leave days. ROI: *infinity*. I had discovered infinity. In a holiday calendar. I pushed back from my desk and stared at the spreadsheet with the reverence of a man who has found religion in a PDF." },

    { type: "body", text: "I did the math. Our company gave us eighteen days of annual leave. A normal person would use these for family visits, medical emergencies, and the occasional pre-planned vacation. I was no longer a normal person. I was a person who had stood in the rain in Makkandur with forty-seven rupees and survived, and this had given me a specific kind of courage\u2014not the courage to climb mountains or face danger, but the courage to *use my leave*. Which, in corporate India, is its own form of rebellion." },

    { type: "body", text: "Eight leave days. That was all I needed. Eight strategically placed leave days, slotted into the gaps around public holidays and weekends, would give me twenty-four travel days spread across the year. Twenty-four days. Three full weeks of travel. Using only eight days of leave and losing zero working days to the mysterious productivity gods that Vikram worshipped." },

    { type: "body", text: "I color-coded the spreadsheet. Weekends were grey. Public holidays were blue. My leave days were orange. And the resulting trip windows\u2014the glorious, engineered four-day and five-day stretches\u2014were green. The calendar looked like a quilt, and I was the most excited I\u2019d been since the Hampi booking." },

    { type: "break" },

    { type: "first", text: "The first engineered long weekend was Republic Day. Thursday, January 26th: public holiday. Friday, January 27th: one day of leave. Saturday and Sunday: the weekend that was already mine. Four days. And I knew exactly where I was going." },

    { type: "body", text: "Back to Hampi." },

    { type: "body", text: "I know what you\u2019re thinking. Of all the places in India\u2014and there are, by some estimates, more destinations in this country than any single human could visit in a lifetime\u2014why return to the one place I\u2019d already been? The answer was simple: Hampi deserved a second visit. The first time, I\u2019d been a tourist. I\u2019d been nervous, over-packed, and so busy processing the novelty of being alone that I\u2019d missed half of what was in front of me. This time, I would be a *traveler*. I knew the difference now, or at least I thought I did, which is close enough." },

    { type: "body", text: "The train ticket was Rs. 385. Sleeper Class, Yeshwantpur to Hospet, departing at 10 PM, arriving at 6 AM. Three hundred and eighty-five rupees. I\u2019d spent more than that on a single Swiggy order the previous weekend\u2014a large pizza and garlic bread that I\u2019d eaten alone in my PG room while watching a Netflix show I can\u2019t even remember now. The economics of travel, I was learning, were not what I\u2019d assumed. Travel was not expensive. *Staying home* was expensive. Staying home cost you nothing in rupees and everything in stories." },

    { type: "body", text: "The difference between first-trip terror and second-trip confidence was startling. At Yeshwantpur station, I moved through the crowd with the easy familiarity of a man who had done this before\u2014which I had, exactly once, but once was enough to replace confusion with competence. I found my coach without asking anyone. I knew to bring my own bedsheet. I knew the chai vendor would come through at 5:30 AM and that the correct price was ten rupees, not the thirty the vendor would attempt to charge if he thought you were a tourist." },

    { type: "body", text: "I knew that the top berth was the best berth because nobody could sit on it during the day, and I climbed up to it with the satisfaction of a man claiming territory. The train pulled out of Bangalore with a shudder and a long, melancholy whistle, and I lay on my berth and watched the city lights give way to darkness through the small, barred window, and I felt\u2014this is going to sound dramatic, but I mean it\u2014*free*." },

    { type: "body", text: "In Hampi, I rented a bicycle. A Hero Ranger, single-speed, with a seat that had been ergonomically designed to cause maximum discomfort and brakes that worked on a suggestion basis. It cost Rs. 150 per day. And it changed everything." },

    { type: "body", text: "On my first trip, I\u2019d walked or taken autos, which meant I\u2019d seen the major sites in a linear sequence: Virupaksha Temple, Vittala Temple, the elephant stables, done. On a bicycle, the ruins opened up. I pedaled down dirt roads between boulder fields, past banana groves and rice paddies, finding temples I hadn\u2019t known existed\u2014small, half-buried, overgrown with vines, their carved walls visible only when you were close enough to touch them." },

    { type: "body", text: "I found the Malyavanta Raghunathaswamy Temple at 3 PM on a Friday, when the only other person there was the priest, who was asleep. The temple sat on a hill overlooking the river, surrounded by boulders that had been carved with images of Rama and Hanuman centuries ago. The carvings were worn smooth by time and weather, but you could still trace the outlines with your fingers\u2014a raised arm here, a curved tail there, the ghost of a story preserved in stone." },

    { type: "body", text: "The priest woke up when I accidentally kicked a stone. He blinked at me, assessed me as non-threatening, and went back to sleep. I sat on the temple steps for an hour, looking at the river, and thought about absolutely nothing. This was becoming a skill I was developing: the ability to sit still and think about nothing. In Bangalore, every idle moment was colonized by a notification or a thought about a task or a vague anxiety about something I\u2019d forgotten to do. Here, the nothing stayed nothing. It was clean." },

    { type: "break" },

    { type: "first", text: "The train conversation happened on the way back. She was sitting in the berth across from mine\u2014a woman in her early thirties, dressed in a salwar kameez with the slightly rumpled look of someone who had also been traveling for several days. A three-year-old boy was asleep in her lap, his face pressed against her dupatta, one small hand gripping her sleeve with the unconscious possessiveness of a child who is not letting go even in sleep." },

    { type: "body", text: "She introduced herself as Kavitha. She was from Hyderabad. She worked in HR\u2014\u201Cthe irony of which,\u201D she said, \u201Cis not lost on me.\u201D She had been traveling solo with her son for the past five days\u2014Hampi, Badami, Aihole\u2014a circuit she did every year during the Republic Day long weekend." },

    { type: "body", text: "\u201CEvery year?\u201D I was genuinely surprised. Solo travel with a toddler seemed to me like an exercise in advanced masochism, the logistical equivalent of juggling chainsaws while riding a unicycle." },

    { type: "body", text: "She laughed. \u201CYou learn to plan around nap times,\u201D she said. \u201CEverything happens between naps. He sleeps, I read. He\u2019s awake, we explore. It\u2019s actually easier than traveling with adults. Adults have opinions. He just wants to throw rocks at things.\u201D" },

    { type: "body", text: "I told her about my spreadsheet. She nodded, not with the indulgent skepticism I\u2019d expected but with the recognition of a fellow practitioner. \u201CYou\u2019re not the first person to figure this out,\u201D she said. \u201CThere\u2019s a whole community. We call ourselves the Sandwich Day People.\u201D" },

    { type: "body", text: "\u201CSandwich days?\u201D" },

    { type: "body", text: "\u201CThe working days between a holiday and a weekend. Monday between a Sunday and a Tuesday holiday. Friday between a Thursday holiday and a Saturday. They\u2019re the bread. The trip is the filling. You take one day of leave and you get four days of travel. That\u2019s a sandwich.\u201D She said this with the quiet authority of a woman who had elevated leave-optimization to an art form." },

    { type: "body", text: "Her system was more sophisticated than mine. She had mapped the holiday calendars of three years in advance, cross-referenced them with school holidays (for when her son was older), identified recurring patterns (\u201CRepublic Day almost always gives you a good one\u201D), and maintained a running list of destinations organized by duration: two-day trips, three-day trips, four-day trips, and the rare, magnificent five-day trip that required only two leave days and felt like stealing." },

    { type: "body", text: "\u201CAnd you don\u2019t feel guilty?\u201D I asked, because the guilt was something I hadn\u2019t mentioned yet but that sat in my chest every time I submitted a leave request. The guilt of not being at my desk. The guilt of colleagues who might have to cover for me. The guilt that Indian work culture has embedded so deep in its professional class that taking your own leave feels like a transgression." },

    { type: "body", text: "Kavitha looked at me over her sleeping son\u2019s head with an expression that was patient but firm. \u201CNever feel guilty,\u201D she said. \u201CYou have the leave. The company gave it to you. It\u2019s in your contract. It\u2019s part of your compensation. Would you feel guilty about spending your salary? Then why feel guilty about spending your leave?\u201D She paused. \u201CThe company is not going to collapse because you took a Friday off. And if it does, that\u2019s the company\u2019s problem, not yours.\u201D" },

    { type: "body", text: "Her son stirred in his sleep, rearranged himself against her dupatta, and went still again. The train rocked gently. Outside the window, the Karnataka scrubland was giving way to the first suburbs of Bangalore\u2014construction sites and apartment complexes rising out of what had recently been farmland, the city advancing like an army." },

    { type: "body", text: "\u201COne more thing,\u201D Kavitha said, as the train slowed. \u201CDon\u2019t tell HR about the spreadsheet.\u201D She grinned. \u201CThat\u2019s my department. We wouldn\u2019t approve of it.\u201D" },

    { type: "break" },

    { type: "first", text: "The long weekends became a rhythm. Not a habit\u2014a habit is brushing your teeth, something you do without thinking. This was more intentional than that. It was a practice, the way meditation is a practice or music is a practice: something you got better at with repetition, something that rewarded consistency, something that slowly changed the shape of your life." },

    { type: "body", text: "March: Pondicherry. Holi fell on a Monday, so I had three days without taking any leave. I took the overnight bus from Bangalore on Friday night, arrived Saturday morning, and spent three days walking the French Quarter, eating dosas the size of my arm, sitting on the Rock Beach promenade at dawn watching the Bay of Bengal turn colors I didn\u2019t know the sea could produce. The total cost, including bus, hostel, and food: Rs. 4,200. The ROI: infinite, because zero leave days used." },

    { type: "body", text: "April: Nilgiris. One day of leave on Friday, attached to a Saturday and Sunday, gave me three days in the tea country. I took the Nilgiri Mountain Railway from Mettupalayam to Ooty\u2014the toy train, the UNESCO one, the one that climbs through eucalyptus forests and tea plantations with the patient determination of a machine that has been doing this since 1908. The train took five hours to cover forty-six kilometres. I watched the landscape change with every hundred feet of elevation gained, from tropical plains to temperate forests to the almost-English rolling hills of the Nilgiris, and I thought: *this is what time is supposed to feel like*." },

    { type: "body", text: "June: Gokarna. A weekend trip, no leave needed. Two nights in a beach shack that cost Rs. 600 per night and had a view of the Arabian Sea from the bed. I trekked from Om Beach to Half Moon Beach to Paradise Beach, each one emptier and more beautiful than the last, until at Paradise Beach there was nobody at all\u2014just sand and water and a cliff face and me. I swam alone in the sea for an hour and felt, for the first time, the particular freedom of being in a place where nobody knows where you are and nobody needs you to be anywhere." },

    { type: "body", text: "None of these were Instagram-worthy \u201Conce in a lifetime\u201D trips. Nobody would make a YouTube video about a three-day weekend in Gokarna. There were no Himalayan sunrises, no life-threatening disasters, no profound encounters with wise strangers. These were small trips. Quick trips. The kind of trip that fits in the margin between one working week and the next, the way a good sentence fits in the margin of a page." },

    { type: "body", text: "But stacked together, they were something else. Stacked together\u2014Pondicherry in March, Nilgiris in April, Gokarna in June, and the half-dozen other weekends I\u2019d tucked into the gaps of the calendar\u2014they were a life lived with curiosity. Not a life lived on vacation. Not a life lived running away from work. A life lived *between* work, in the spaces that had always been there but that I\u2019d never thought to fill with anything other than laundry and Netflix and the vague, low-grade dissatisfaction of unused time." },

    { type: "body", text: "My colleague Arjun was the first to notice. Arjun sat two desks away from me and had the observational skills of a surveillance camera. \u201CDude,\u201D he said one Monday morning, leaning back in his chair and studying me with the narrowed eyes of a man piecing together a conspiracy. \u201CYou\u2019re always *just back from somewhere*. How? Do you not work?\u201D" },

    { type: "body", text: "I pulled up the spreadsheet. I showed him the color-coding. I walked him through the sandwich-day logic, the ROI column, the annual plan that turned eighteen leave days into what amounted to a parallel life of travel. Arjun stared at the screen for thirty seconds, which is a long time for a man who usually context-switches every eleven seconds. Then he said, very quietly: \u201CSend me this.\u201D" },

    { type: "body", text: "I sent it to him. He sent it to his friend in the QA team. The QA friend sent it to the design team. Within two weeks, seventeen people in our company had a copy of my spreadsheet, and HR sent a company-wide email titled \u201CReminder: Leave Policy \u2014 Spirit vs. Letter\u201D that was clearly directed at someone but named no one. I printed the email and pinned it to my desk. Arjun high-fived me. It was, in its small way, a revolution." },

    { type: "body", text: "The long weekends were working. The spreadsheet was filling up. My Slack status toggled between \u201CAvailable\u201D and \u201COut of Office\u201D with a frequency that I\u2019m sure annoyed Vikram but that he never mentioned, because the work was getting done. The PRs were reviewed. The sprints were completed. The retro action items were actioned. I was doing everything I\u2019d always done, but I was also doing something new: I was *leaving*." },

    { type: "body", text: "But I hadn\u2019t yet tested myself against something that could actually break me. The long weekends were gentle. They were trains and buses and beaches and temples\u2014comfortable, manageable, safe. They were travel with training wheels. Somewhere in the back of my mind, I knew that real growth\u2014the kind that changes not just your Instagram grid but your actual understanding of who you are\u2014required something harder." },

    { type: "body", text: "The Himalayas were calling. Or more accurately, a YouTube video with an exclamation mark in the title was calling." },

    { type: "trip", destination: "The Long Weekend Playbook", items: [
      ["The Strategy", "Map every public holiday to its nearest weekend. Identify \u201Csandwich days\u201D\u2014single working days between a holiday and a weekend. One leave day = four trip days. Two leave days = five trip days."],
      ["The Math", "18 annual leave days, strategically placed, yield 20\u201324 travel days per year. That\u2019s roughly one trip every 2\u20133 weeks."],
      ["Best Holidays", "Republic Day (Jan 26), Holi (varies), Independence Day (Aug 15), Gandhi Jayanti (Oct 2), Diwali (varies), Christmas (Dec 25). Check your company\u2019s restricted holidays for bonus days."],
      ["Budget Hack", "Long weekends are cheaper than long vacations. You don\u2019t need flights\u2014most weekend-worthy destinations are 4\u20138 hours by bus or train from major cities. Average cost: Rs. 3,000\u20137,000."],
      ["Booking Tip", "Book transport the moment the holiday calendar is released. Train tickets for Republic Day weekend sell out in minutes. Be at IRCTC at 10 AM on release day. This is not optional."],
      ["The Guilt", "Your leave is part of your compensation. You earned it. Use it. The company will survive your Friday absence."],
      ["One Rule", "Never cancel a long weekend for work. The work will be there on Monday. The Pondicherry sunset will not."],
    ]},
  ];
}

function chapter4() {
  return [
    { type: "heading", number: 4, title: "The 3 AM Himalayan Mistake" },

    { type: "first", text: "The alarm went off at 3 AM, and for a full ten seconds I didn\u2019t know where I was. This is not a figure of speech. I genuinely, completely, existentially did not know where I was. The sleeping bag was zipped up to my chin. The air inside the tent was so cold it felt like breathing glass. My toes\u2014I tried to wiggle them and received no response, as if my feet had seceded from my body during the night and were now operating as an independent, frozen republic." },

    { type: "body", text: "Outside, the wind was doing something aggressive to the tent fabric, a relentless *flap-flap-flap* that sounded like a trapped bird. Someone in a nearby tent was coughing with the deep, hollow resonance of a person who had also made questionable life decisions. And above it all, the silence. Not city silence, which is really just the ambient noise of millions of people existing in proximity. Mountain silence. The kind that has weight. The kind that presses against your eardrums and makes you aware that you are a very small, very warm thing in a very large, very cold place." },

    { type: "body", text: "Then I remembered. I was at 12,500 feet above sea level, camped on a ridge in the Dhauladhar range of the Himalayas, approximately halfway up a mountain called Triund. My tent was a rented, two-person affair that smelled like mildew and someone else\u2019s socks. The temperature was minus five degrees Celsius. And in approximately one hour, I was supposed to unzip this sleeping bag, put on boots that would be frozen stiff, and walk the final stretch to the summit in the dark to watch the sunrise." },

    { type: "body", text: "I lay still and conducted a thorough inventory of my regrets. There were many, and they were specific. I regretted the YouTube video. The YouTube video was the original sin, the serpent in my personal garden, and it had a title that I can still recite from memory because it had been seared into my brain by the events that followed: \u201CTriund Trek \u2014 How Hard Can It Be?! \ud83c\udfd4\ufe0f EASIEST Himalayan Trek!\u201D The exclamation marks. The emoji. The word *easiest*, deployed with the reckless confidence of a content creator whose body fat percentage was in the single digits." },

    { type: "body", text: "The video had shown a cheerful young man bounding up a mountain trail in what appeared to be athleisure wear, pausing occasionally to address the camera with observations like \u201Cgreat trail!\u201D and \u201Camazing views!\u201D He was not sweating. He was not gasping for air. At no point did he stop to hold his knees and contemplate the choices that had led him to this moment. The comments section was full of people confirming that yes, Triund was easy, Triund was a \u201Cbeginner trek,\u201D Triund was \u201Cperfect for first-timers.\u201D" },

    { type: "body", text: "I was a first-timer. I was, specifically, a first-timer whose primary form of exercise was walking from my desk to the office cafeteria\u2014a distance of approximately sixty metres, much of it horizontal. I ran 2K on the treadmill twice a week, a fact I had told myself constituted \u201Cfitness\u201D the way a person who has read one Wikipedia article tells themselves they understand quantum physics. Two kilometres on a flat, climate-controlled treadmill was not preparation for nine kilometres uphill at altitude. I would discover this, with the brutal clarity of experience, approximately four hours into the trek." },

    { type: "body", text: "But at the moment of booking\u2014three weeks before the frozen tent, three weeks before the altitude headache, three weeks before the moment on the false summit where I genuinely, seriously, with full conviction considered quitting\u2014I was invincible. I had survived Hampi and Coorg. I had engineered long weekends. I had a spreadsheet. What was a mountain?" },

    { type: "break" },

    { type: "first", text: "The journey to the mountain was its own kind of odyssey. Thursday evening: a flight from Bangalore to Delhi, cheap enough that I suspect the airline was losing money on each passenger and making it up in baggage fees. Thursday night: an overnight Volvo bus from ISBT Kashmere Gate to Dharamshala, departing at 8 PM, arriving\u2014theoretically\u2014at 7 AM. The bus was a semi-sleeper, which is Indian transportation\u2019s way of saying \u201Cneither seated nor horizontal, in a liminal zone of discomfort that precludes both rest and activity.\u201D" },

    { type: "body", text: "I slept in bursts of twenty minutes, interrupted by speed breakers, truck horns, and the gentle but persistent sliding of my body toward the aisle each time the bus took a curve, which it did approximately every forty seconds because the road from Delhi to Dharamshala is essentially a continuous curve with occasional straight sections included as a form of psychological relief." },

    { type: "body", text: "McLeod Ganj at 8 AM was cold and clean and utterly unlike any place I\u2019d been. The air was thin in a way I could feel\u2014not painful, but *different*, as if someone had subtracted something from the atmosphere that I\u2019d never noticed until it was gone. The streets were narrow and steep and lined with Tibetan prayer flags\u2014strings of red, blue, yellow, green, and white fluttering in the mountain breeze, their colors so bright against the grey stone buildings that they looked hand-painted onto the morning." },

    { type: "body", text: "Monks in maroon robes walked in pairs, their shaved heads gleaming. A man was making momos in a glass-walled kitchen, his hands moving with the mechanical precision of someone who has folded ten thousand dumplings and could fold ten thousand more. The smell\u2014ginger, garlic, steamed dough, and the clean bite of mountain air\u2014made my stomach growl with an intensity that startled the woman walking next to me." },

    { type: "body", text: "I sat at a small cafe and ordered a plate of steamed momos and a glass of lemon-ginger-honey tea, which is the unofficial beverage of the Himalayan foothills and which I would consume in quantities that bordered on medical during the next three days. The momos were perfect\u2014the skin thin and slightly translucent, the filling fragrant with ginger and a hint of Sichuan pepper, the chili sauce on the side thick and red and dangerous. I ate them slowly, watching the street, telling myself that my fitness was \u201Cadequate.\u201D" },

    { type: "body", text: "It was not adequate. But I didn\u2019t know that yet. I was still the protagonist of my own YouTube video, the one where everything goes smoothly and the mountain is easy and the sunrise at the top is worth it and nobody mentions the part where you lose a toenail." },

    { type: "break" },

    { type: "first", text: "The trek began at 10 AM from Galu Devi temple, which marked the end of the road and the beginning of the trail. Our group was a loose collection of eight strangers who had signed up with the same trekking company: two software engineers from Pune, a married couple from Jaipur, a solo woman from Mumbai who carried a backpack that was twice the size of mine and moved with the quiet efficiency of someone who had done this before, and three college students from Chandigarh who had brought a portable Bluetooth speaker and apparently intended to provide the soundtrack for the entire mountain." },

    { type: "body", text: "Our guide was a nineteen-year-old named Raju who weighed approximately fifty kilograms and moved uphill with the effortless grace of a creature that had been specifically evolved for this terrain. Raju wore a thin fleece jacket and running shoes\u2014not trekking shoes, not hiking boots, just regular shoes you\u2019d wear to a market\u2014and carried a twenty-kilogram pack on his back as if it contained tissue paper. He looked at our group, assessed our footwear and fitness levels with a single glance, and set a pace that was approximately one-third of what he was capable of, which was still too fast for me." },

    { type: "body", text: "The first two hours were beautiful. I want to emphasize this because what came later was not beautiful, and the beauty of the beginning is what makes the suffering of the middle feel like a betrayal. The trail wound through a pine forest\u2014not the decorative pines of a Bangalore park but massive, ancient Himalayan pines, their trunks straight as columns, their canopy filtering the morning sun into shafts of gold that cut through the mist like searchlights. The air smelled like resin and cold earth and something else, something I couldn\u2019t name but that I\u2019d later learn was simply *altitude*\u2014the smell of air that has fewer things in it." },

    { type: "body", text: "The college students from Chandigarh walked ahead, their Bluetooth speaker playing a Bollywood medley that echoed through the pines. Under other circumstances, I might have found this annoying. Here, with the trees and the mist and the mountain rising above us, it was oddly perfect\u2014a reminder that this was India, and even in the Himalayas, someone was going to play \u201CKesariya\u201D at full volume." },

    { type: "body", text: "At the two-hour mark, the trail turned. Not gradually\u2014suddenly, as if the mountain had been lulling us with gentle inclines and had now decided to reveal its true nature. The path steepened into a series of rocky switchbacks that climbed at an angle my legs had never been asked to negotiate. The pine forest thinned, replaced by scrubby rhododendrons and exposed rock. The sun, which had been pleasant in the forest, was now directly overhead and merciless." },

    { type: "body", text: "My breathing changed. In the forest, I\u2019d been breathing normally\u2014through my nose, without thinking about it, the way you breathe when your body is doing something it considers routine. Now I was breathing through my mouth, in gulps, each breath slightly insufficient, as if the air had been diluted. My heart was hammering at a rate that would have alarmed a cardiologist. My thighs were burning with the specific, acidic burn of muscles being asked to do something they have never practiced." },

    { type: "body", text: "I stopped every fifty steps to catch my breath. Then every thirty steps. Then every twenty. The college students pulled ahead. The married couple from Jaipur pulled ahead. The solo woman from Mumbai was already out of sight, having apparently decided that the group pace was an insult to her capabilities. Even one of the Pune software engineers, a man who had confided at the start that he \u201Chadn\u2019t exercised since college,\u201D was now ten minutes ahead of me. I was last. I was last on a beginner trek." },

    { type: "body", text: "The altitude headache arrived at about 10,000 feet. It started as a dull pressure behind my eyes\u2014the kind of headache you might mistake for dehydration or fatigue\u2014and evolved, over the next hour, into a persistent, pulsing throb that synchronized with my heartbeat. Every step sent a small shockwave through my skull. The world took on a slightly unreal quality, as if I were watching myself from a short distance away, a spectator at my own suffering." },

    { type: "body", text: "At the three-hour mark, a porter passed me going uphill. He was carrying an entire kitchen on his back\u2014a steel trunk, a gas cylinder, pots, pans, utensils, provisions, all of it lashed together with rope and balanced on a wooden frame. He was wearing sandals. *Sandals.* Not trekking sandals, not sport sandals\u2014the kind of rubber sandals you buy at a roadside stall for fifty rupees. And he was moving uphill faster than me, steadily and without visible effort, his breathing even, his face calm." },

    { type: "body", text: "He saw me hunched over at the side of the trail, hands on my knees, breathing like a damaged accordion. He paused. He adjusted the impossible load on his back. And he said, in Hindi so gentle it sounded like a lullaby: \u201C*Aaram se, bhai. Dheere dheere. Pahad bhaagega nahin.*\u201D Take it easy, brother. Slowly, slowly. The mountain isn\u2019t going anywhere." },

    { type: "body", text: "He walked on, his sandals making soft sounds on the rock, his kitchen swaying gently on his back. I watched him disappear around the next switchback and felt two things simultaneously: a deep, bone-level humility, and the irrational but powerful determination to not be outperformed by a man carrying a gas cylinder in sandals." },

    { type: "body", text: "The false summit nearly broke me. The trail leveled out onto a broad, grassy ridge and I thought, with a surge of relief so intense it bordered on religious: *I\u2019ve made it*. Then Raju appeared beside me, pointed to where the trail continued upward for another visible kilometre, and said, \u201CThat\u2019s Triund up there. Maybe one more hour.\u201D" },

    { type: "body", text: "One. More. Hour. I stood on that false summit with my hands on my knees, looking at the real summit taunting me from above, and I considered quitting. Not casually\u2014not the \u201Coh I could quit\u201D that passes through your mind like a cloud. I *seriously* considered it. I calculated the logistics: I could wait here, let the group go on, and walk back down alone. I could tell people I\u2019d done \u201Cmost of Triund.\u201D The false summit was at 11,000 feet. Nobody would know the difference." },

    { type: "body", text: "What kept me going was, I\u2019m ashamed to admit, not courage or determination or some deep well of inner strength. It was embarrassment. I had told three people I was doing this trek: Arjun at work, my PG roommate, and my mother (who had responded with \u201Cbe careful\u201D and a series of prayer emojis). If I quit at the false summit, I would have to tell three people I had quit at the false summit. And the specific, petty shame of that\u2014of being the person who almost did the thing but didn\u2019t\u2014was worse than the headache, worse than the burning thighs, worse than the altitude." },

    { type: "body", text: "So I kept walking. Step. Breathe. Step. Breathe. Step. The trail was steep and rocky and every metre felt like ten. Raju walked beside me, matching my pathetic pace without complaint, occasionally saying things like \u201Cgood, sir, very good\u201D with the patient encouragement of a man talking to a toddler learning to walk." },

    { type: "break" },

    { type: "first", text: "The summit happened at 2 PM. I didn\u2019t arrive at it so much as *collapse* onto it. The trail crested a final ridge and opened onto a broad, flat meadow of brown grass and exposed rock, and I dropped my backpack, sat down on the ground, and cried." },

    { type: "body", text: "Not dramatically. Not with my face in my hands, sobbing. Just tears. Quiet, steady tears that rolled down my cold cheeks and disappeared into the collar of my jacket. I was crying from exhaustion. I was crying from relief. And I was crying from something else\u2014something I couldn\u2019t name then and still can\u2019t name now, but that had something to do with the gap between the person who had stood at the false summit and almost quit and the person who was now sitting here, having not quit. That gap was small\u2014one hour, one decision\u2014but it felt as vast as the valley below." },

    { type: "body", text: "The Dhauladhar range was right there. Not in the distance, not on the horizon, but *right there*\u2014a wall of snow-capped peaks so close it felt like I could reach out and touch them. The mountains rose straight up from the ridgeline, their faces carved by glaciers into vertical cliffs of grey rock and white ice, their summits sharp against a sky so blue it looked synthetic. I had seen mountains before\u2014from car windows, from train windows, from the safe distance at which mountains are scenic. This was different. This was *inside* the mountains. I was at their altitude. I was breathing their air. And they were enormous in a way that made the word \u201Cenormous\u201D feel like a whisper." },

    { type: "body", text: "Below, the Kangra Valley stretched south in layers of green and brown and mist, a patchwork of fields and forests and villages that looked, from this height, like a painting. I could see the silver thread of a river. I could see the white dot of a temple. I could see, or thought I could see, the road we had driven up two days ago, a thin grey line switchbacking up the hillside." },

    { type: "body", text: "\u201CThe mountains don\u2019t care about your designation,\u201D I said, to no one. Raju, who was sitting nearby, looked at me. \u201CSir?\u201D I shook my head. \u201CNothing.\u201D But it wasn\u2019t nothing. It was the truest thing I\u2019d thought all day. The mountains didn\u2019t care that I was a software engineer or that my sprint was behind schedule or that my leave balance was running low. The mountains didn\u2019t care about my performance review or my stock options or the PR that Priya wanted reviewed by Monday. The mountains were twelve thousand feet of granite and snow and geological time, and they did not care, and this not-caring was the most liberating thing I had ever experienced." },

    { type: "body", text: "The camp was set up on the meadow by late afternoon. Raju and the porters assembled tents, boiled water, and produced a dinner of dal, rice, and chapati that was, by any objective culinary standard, unremarkable. I ate it as if it were a Michelin-starred meal, because at 12,500 feet, after six hours of climbing, your body doesn\u2019t care about culinary standards. Your body wants calories. Your body wants warmth. Your body wants to lie horizontal and never move again." },

    { type: "body", text: "Then: the 3 AM alarm. The frozen tent. The regret inventory. The ten seconds of not knowing where I was. And then, because I had already committed to being a person who does uncomfortable things on mountains, I unzipped the sleeping bag, unzipped the tent, and stepped outside." },

    { type: "body", text: "The stars. I need to talk about the stars. These were not Bangalore stars. Bangalore has approximately four visible stars on a clear night, and they are dim and apologetic, as if embarrassed to be seen above a city with so many better-lit alternatives. These were Himalayan stars. There were millions of them\u2014not metaphorically, *literally* millions, a dense, glittering carpet that covered the entire sky from horizon to horizon. The Milky Way was visible not as a faint smudge but as a bright, detailed band of light, a river of stars so thick and luminous that it cast actual shadows on the ground." },

    { type: "body", text: "I stood outside my tent at 3 AM, at minus five degrees, with frozen toes and a throbbing headache, and I looked up, and for a moment\u2014brief, fragile, impossible to hold\u2014I felt the scale of things. Not in an intellectual way, not in the way you understand scale when someone tells you the universe is fourteen billion years old. In a *physical* way. I felt, in my body, how small I was. How small the mountain was. How small everything I had ever worried about was, measured against the cold, indifferent, achingly beautiful vastness of the sky." },

    { type: "body", text: "The sunrise happened at 5:30 AM. I was sitting on a rock with fifteen other trekkers, all of us wrapped in sleeping bags and jackets and blankets, all of us holding cups of chai that were cooling faster than we could drink them. The eastern horizon was a thin line of gold that spread, slowly, the way light spreads in water\u2014outward and upward, turning the deep blue of pre-dawn into pale gold into orange into the full, blazing amber of a Himalayan sunrise." },

    { type: "body", text: "The peaks of the Dhauladhar caught the light and held it. First they were grey. Then they were pink\u2014a soft, impossible pink, the color of the inside of a seashell. Then they were rose. Then gold. The transformation took about ten minutes, and during those ten minutes, nobody spoke. Fifteen strangers, from different cities and different lives, sat in silence and watched mountains change color, and the silence was not awkward but *reverent*\u2014the silence of people witnessing something that does not require commentary." },

    { type: "body", text: "The college student from Chandigarh\u2014the one who had called me \u201Cuncle\u201D the day before, the one with the Bluetooth speaker\u2014sat down beside me. He didn\u2019t say anything. He offered me a piece of Dairy Milk chocolate from a bar that was frozen solid and had to be snapped rather than broken. I took it. We sat in silence, eating frozen chocolate and watching the Himalayas turn gold, and it was\u2014without exaggeration\u2014the most purely beautiful moment of my life." },

    { type: "body", text: "\u201CType 2 fun,\u201D the college student said, after a while." },

    { type: "body", text: "\u201CWhat?\u201D" },

    { type: "body", text: "\u201CType 2 fun. It\u2019s a thing. Type 1 fun is fun while it\u2019s happening\u2014like eating pizza or watching a movie. Type 2 fun is miserable while it\u2019s happening but amazing in retrospect. Like this.\u201D He gestured at the mountains, the sunrise, the frozen chocolate, the fact that we were both sitting on a rock at dawn with numb feet and headaches and stupid grins on our faces. \u201CThis is Type 2 fun.\u201D" },

    { type: "body", text: "He was right. The entire trek\u2014the altitude headache, the false summit, the burning thighs, the 3 AM alarm, the frozen tent\u2014had been miserable. And it was already, even as I sat there still experiencing the last of it, becoming the best thing I had ever done." },

    { type: "break" },

    { type: "first", text: "The descent provided one final gift: a moment of physical humiliation so complete that it has become my go-to anecdote for any conversation about the gap between self-image and reality." },

    { type: "body", text: "We were about an hour from the bottom. The trail was wide and relatively gentle, winding through the pine forest where the trek had begun. I was feeling good\u2014tired, sore, but buoyed by the sunrise and the chocolate and the knowledge that I had, against all expectations and bodily protests, completed the thing. My confidence was, perhaps, slightly higher than was warranted." },

    { type: "body", text: "I was navigating a section of the trail that involved stepping over a series of flat rocks when my left foot\u2014the one with the blister that had been announcing its presence for the past twelve hours\u2014landed on a patch of loose gravel, slipped, and sent me into an uncontrolled, slow-motion fall that I was powerless to stop. I went down sideways, arms flailing, backpack shifting my center of gravity in exactly the wrong direction, and landed on my hip and elbow with a thud that echoed off the trees." },

    { type: "body", text: "The fall itself was not the humiliating part. Falls happen on treks. Raju helped me up, checked that nothing was broken, brushed pine needles off my jacket. The humiliating part was the audience. A group of about twelve trekkers\u2014a fresh group, heading *up*, clean and energetic and wearing matching T-shirts from what appeared to be a corporate offsite\u2014had rounded the corner at the exact moment of my fall and had witnessed the entire performance. They stood there, matching T-shirts bright in the forest light, and stared at me with the polite concern of people trying very hard not to laugh." },

    { type: "body", text: "\u201CI\u2019m fine,\u201D I said, which is what you say when you are not fine but would prefer the moment to end. One of them\u2014a woman with a ponytail and the sympathetic expression of someone who has watched many people fall\u2014said, \u201CIt\u2019s the downhill that gets you.\u201D I nodded as if this was wisdom and not just a statement of the obvious." },

    { type: "body", text: "Back in McLeod Ganj that evening, I limped to a restaurant, ordered a plate of momos and a lime soda, and sat by the window taking stock. My left elbow was bruised a spectacular purple. My right big toenail was, I discovered in the shower that evening, going to fall off within the week\u2014a parting gift from the new trekking shoes that I had broken in for a total of twenty minutes on my PG room floor. My thighs were so sore that sitting down on the toilet required a strategic lowering maneuver that took approximately fifteen seconds." },

    { type: "body", text: "I was, by any reasonable metric, a physical wreck. And I was happier than I\u2019d been in months. The mountains had tested my body\u2014tested it honestly, without allowances for my office job or my treadmill routine or my conviction that 2K counted as fitness\u2014and my body had passed. Barely. Ungracefully. With crying and falling down and being called uncle by a teenager. But it had passed." },

    { type: "body", text: "My phone buzzed with a message from Arjun: \u201CHow was the trek?\u201D I typed back: \u201CType 2 fun.\u201D He sent back a question mark. I decided to explain later." },

    { type: "body", text: "The mountains had tested my body. But it was a temple town in the south that would test my patience\u2014and introduce me to the best meal of my life." },

    { type: "trip", destination: "Triund (via McLeod Ganj / Dharamshala)", items: [
      ["Duration", "4 days (Thursday evening to Sunday). Thu: fly to Delhi, overnight bus to Dharamshala. Fri: acclimatize in McLeod Ganj. Sat: trek to summit, camp overnight. Sun: descend, bus back."],
      ["Budget", "Rs. 8,000\u201312,000 from Delhi (includes bus, trek fee with guide/tent/meals, accommodation in McLeod Ganj, food, and momos budget)"],
      ["Best Season", "March\u2013May (wildflowers, clear skies) or September\u2013November (post-monsoon clarity, snow on peaks). Avoid June\u2013August (monsoon makes the trail dangerous) and December\u2013February (extreme cold, trail may be snow-covered)."],
      ["Getting There", "Overnight Volvo bus from Delhi ISBT to Dharamshala (Rs. 800\u20131,500, 10\u201312 hours). Auto or taxi from Dharamshala to McLeod Ganj (Rs. 200\u2013300, 30 minutes). Trek starts from Galu Devi temple, 2 km above McLeod Ganj."],
      ["Difficulty", "Moderate. 9 km one way, 5\u20136 hours up, 3\u20134 hours down. Elevation gain: ~3,500 feet. No technical skills required, but basic fitness is non-negotiable. Your treadmill 2K does not count. (I learned this the hard way.)"],
      ["Must-Try Food", "Steamed momos and lemon-ginger-honey tea at any cafe in McLeod Ganj. Thukpa (Tibetan noodle soup) on a cold evening. The chai at the midway dhaba on the trek\u2014overpriced, over-sweet, and the best chai you will ever drink."],
      ["One Tip", "Start the summit push at 4 AM for sunrise. Carry a headlamp, not your phone flashlight\u2014you\u2019ll need your phone battery for the photos you\u2019ll want to take at the top. And break in your trekking shoes for at least two weeks before the trek. Your toenails will thank you."],
    ]},
  ];
}

module.exports = { chapter1, chapter2, chapter3, chapter4 };
